version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/data
    environment:
      - NODE_ENV=production
      - TYPEORM_CONNECTION=sqlite
      - TYPEORM_DATABASE=/data/db.sqlite
      - PORT=8000

volumes:
  sqlite-data: